// dev/fixtures-panels/index.js — fixture loader for dev/panels-preview.html: the shared fixtures
// (dev/fixtures/) plus the panel-specific ones generated by dev/panels-fixtures.mjs.
import * as shared from '../fixtures/index.js?shared'; // query string: not caught by the import map

const BASE = new URL('./', import.meta.url);
export const freshen = shared.freshen;

export async function listFixtures() {
  const [a, b] = await Promise.all([
    shared.listFixtures(),
    fetch(new URL('manifest.json', BASE), { cache: 'no-store' }).then((r) => (r.ok ? r.json() : [])),
  ]);
  return [...b, ...a];
}

export async function loadFixture(name) {
  if (String(name).startsWith('p-')) {
    const res = await fetch(new URL(name + '.json', BASE), { cache: 'no-store' });
    if (!res.ok) throw new Error('Unknown fixture “' + name + '” — run: node dev/panels-fixtures.mjs');
    return res.json();
  }
  return shared.loadFixture(name);
}
